### ISSUE TITLE
Args out of range: 0,0

### ISSUE THREAD

**Issue by kostajh** [lepisma/emacs-speech-input#4]
I see this in the `*Messages*` buffer when attempting to dictate:

```
[esi] Starting dictation mode ...
[esi] Dictation mode ready to use.
error in process filter: esi-dictate-insert: Args out of range: 0, 0
error in process filter: Args out of range: 0, 0
```

`dg.py` seems to work OK.

**Comment by lepisma** [comment]
It seems to work at the moment. Can you enable debug and run this again and let me know where the error is coming from?

**Comment by kostajh** [comment]
Sure, the error is:

```
Debugger entered--Lisp error: (args-out-of-range 0 0)
  get-text-property(0 esi-dictate-transcription-item)
  esi-dictate-insert(((channel (alternatives . [((transcript . "Test.") (confidence . 0.69042593) (words . [...]))])) (metadata (model_info (name . "2-general-nova") (version . "2024-01-11.36317") (arch . "nova-2")) (request_id . "f4dc1260-2424-4d31-a419-78f3d6c7bf3d") (model_uuid . "1dbdfb4d-85b2-4659-9831-16b3c76229aa")) (type . "Results") (channel_index . [0 1]) (duration . 2.93) (start . 0.0) (is_final . t) (from_finalize . :false) (speech_final . t)))
  esi-dictate-filter-fn(#<process esi-dictate-dg> "Output: {\"channel\": {\"alternatives\": [{\"transcript...")
```

Maybe I have something wrong with the OpenAI integration, as `curl "https://api.openai.com/v1/chat/completions"` is returning an insufficient quota error (even though I've just bought $10 of credits).

**Comment by lepisma** [comment]
Okay this is a bug when the voice cursor is at (point-min) of the buffer. Since the code tries to look behind the voice cursor for some edits, this fails.

I will fix it in a day or so.

Thanks for reporting.

**Comment by janaab11** [comment]
picking this up. should close by tomorrow

**Comment by kostajh** [comment]
> Okay this is a bug when the voice cursor is at (point-min) of the buffer. Since the code tries to look behind the voice cursor for some edits, this fails.

Oops, yes, that is definitely the issue. Everything works fine if I have the cursor a few lines down.
